export default [
  { category: 1, title: 'Куриная печень', slug: 'chicken-3' },
  { category: 1, title: 'Свиные ребра', slug: 'pork-15' },
  { category: 1, title: 'Баранина (фарш)', slug: 'lamb-10' },
  { category: 1, title: 'Баранина', slug: 'lamb-12' },
  { category: 1, title: 'Баранье сердце', slug: 'lamb-6' },
  { category: 1, title: 'Бекон', slug: 'bacon' },
  { category: 1, title: 'Говядина', slug: 'beef-13' },
  { category: 1, title: 'Говяжья печень', slug: 'beef-7' },
  { category: 1, title: 'Говяжьи почки', slug: 'beef-6' },
  { category: 1, title: 'Говяжье сердце', slug: 'beef-9' },
  { category: 1, title: 'Говяжий язык', slug: 'beef-3' },
  { category: 1, title: 'Говяжьи ребра', slug: 'beef-43' },
  { category: 1, title: 'Говядина (фарш)', slug: 'beef-18' },
  { category: 1, title: 'Индейка (грудка)', slug: 'turkey-5' },
  { category: 1, title: 'Индейка (крылышки)', slug: 'turkey-6' },
  { category: 1, title: 'Индейка (ножки)', slug: 'turkey-3' },
  { category: 1, title: 'Индейка (окорочка)', slug: 'turkey-4' },
  { category: 1, title: 'Индейка (фарш)', slug: 'turkey-7' },
  { category: 1, title: 'Индейка (целиком)', slug: 'turkey-whole' },
  { category: 1, title: 'Карбонад', slug: 'brisket-4' },
  { category: 1, title: 'Курица (бедро)', slug: 'chicken-thigh' },
  { category: 1, title: 'Курица (голень)', slug: 'chicken-leg' },
  { category: 1, title: 'Курица (грудка)', slug: 'chicken-8' },
  { category: 1, title: 'Курица (желудочки)', slug: 'chicken-7' },
  { category: 1, title: 'Курица копечная', slug: 'chicken-26' },
  { category: 1, title: 'Курица (крылышки)', slug: 'chicken-6' },
  { category: 1, title: 'Курица (сердце)', slug: 'chicken-4' },
  { category: 1, title: 'Курица (целиком)', slug: 'chicken-20' },
  { category: 1, title: 'Курица (фарш)', slug: 'chicken-12' },
  { category: 1, title: 'Курица (филе)', slug: 'chicken-1' },
  { category: 1, title: 'Сало', slug: 'pork-17' },
  { category: 1, title: 'Свинина', slug: 'pork-22' },
  { category: 1, title: 'Свинина (вырезка)', slug: 'pork-28' },
  { category: 1, title: 'Свинина (сердце)', slug: 'pork-16' },
  { category: 1, title: 'Свинина (фарш)', slug: 'pork-19' },

  { category: 2, title: 'Сёмга', slug: 'salmon-6' },
  { category: 2, title: 'Горбуша свежая', slug: 'hunchback-salmon-1' },
  { category: 2, title: 'Консервированная рыба (тунец)', slug: 'tuna-3' },
  { category: 2, title: 'Форель', slug: 'trout' },
  { category: 2, title: 'Мидии', slug: 'mussel' },
  { category: 2, title: 'Кальмары консервированные', slug: 'quid-7' },
  { category: 2, title: 'Нори', slug: 'nori' },
  { category: 2, title: 'Хек', slug: 'hake-1' },
  { category: 2, title: 'Окунь', slug: 'perch-5' },
  { category: 2, title: 'Треска (филе)', slug: 'cod-1' },
  { category: 2, title: 'Морская капуста', slug: 'laminaria' },
  { category: 2, title: 'Минтай (филе)', slug: 'pollack-5' },
  { category: 2, title: 'Щука', slug: 'pike-1' },
  { category: 2, title: 'Дорадо', slug: 'dorado' },
  { category: 2, title: 'Навага', slug: 'navaga-3' },
  { category: 2, title: 'Пикша', slug: 'haddock' },
  { category: 2, title: 'Кальмары свежие / мороженые', slug: 'quid-2' },
  { category: 2, title: 'Анчоусы', slug: 'anchovies-fillets' },
  { category: 2, title: 'Икра осетровая', slug: 'caviar-3' },
  { category: 2, title: 'Икра черная', slug: 'caviar-2' },
  { category: 2, title: 'Камбала свежая', slug: 'sole-1' },
  { category: 2, title: 'Крабовое мясо', slug: 'crab-3' },
  {
    category: 2,
    title: 'Креветки свежие (очищенные)',
    slug: 'peeled-shrimps-2',
  },
  { category: 2, title: 'Лосось (филе)', slug: 'salmon-fillets' },
  { category: 2, title: 'Морской гребешок', slug: 'scallop-1' },
  { category: 2, title: 'Сельд свежая', slug: 'herring-1' },
  { category: 2, title: 'Тилапия (тиляпия)', slug: 'tilapia-1' },
  { category: 2, title: 'Скумбрия свежая', slug: 'mackerel-1' },
];
